name: Deploy Chess

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted


  steps:
    - name: Deploy Chess
      run: |
        cd /var/www/chess-new
        git pull origin main
        docker compose -f compose.simple.yml up -d --build

